ADMIN_EMAIL = "admin"
ADMIN_PASSWORD = "$2a$12$LBI3KVAqeS2F2Ij6c8aSreswm0B3leKmznmN4H94TaUWG5gkH69v."

SENDER_EMAIL = "dynatrade.dubai@gmail.com"
SENDER_APP_PASSWORD = "jpxz vaps vjed fntm"

ENCRYPTION_KEY = "DSLGvYQvAOhUQAlpyIfCwTc-270vpqYApSJMU7SMTtM="
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
